name: Coverage CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build-gcc9-coverage:
    runs-on: ubuntu-20.04
    name: GNU GCC 9 and run coverage
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build lorina
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_COMPILER=g++-9 -DLORINA_TEST=ON -DENABLE_COVERAGE=ON ..
        make run_tests
    - name: Run tests
      run: |
        cd build
        ./test/run_tests
    - name: Run lcov
      run: |
        sudo apt-get install lcov
        lcov -t "result" -o lcov.info -c -d .
        lcov -e lcov.info "*lorina/include*" -o lcov_filtered.info
        lcov -l lcov_filtered.info
    - name: CodeCov
      run: |
        export CODECOV_TOKEN="f21e7158-333c-40ed-b0fd-8dda95ec1d02"
        bash <(curl -s https://codecov.io/bash) -f lcov_filtered.info || echo "Codecov did not collect coverage reports"
