name: MacOS CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build-gcc10:
    name: GNU GCC 10
    runs-on: macOS-11

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build lorina
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_COMPILER=$(which g++-10) -DLORINA_TEST=ON ..
        make run_tests
    - name: Run tests
      run: |
        cd build
        ./test/run_tests
  build-gcc11:
    name: GNU GCC 11
    runs-on: macOS-11

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build lorina
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_COMPILER=$(which g++-11) -DLORINA_TEST=ON ..
        make run_tests
    - name: Run tests
      run: |
        cd build
        ./test/run_tests
build-clang:
    name: Clang 12
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build lorina
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DLORINA_TEST=ON ..
        make run_tests
    - name: Run tests
      run: |
        cd build
        ./test/run_tests
